### ISSUE TITLE
Is there any plan to add `getETFDetails` endpoint to the javascript client?

### ISSUE THREAD

**Issue by mehdi-loup** [barchart/barchart-ondemand-client-js#1]
This method is part of the documentation but not of  the javascript client http://www.barchartondemand.com/get/etfdetails.php
I can make a PR if wanted

**Comment by mvberg** [comment]
Yes. In the interim you can you the generic 'get' function - something like:

`client.get('getETFDetails', {symbol:'SPY'}, function(err, data){
});`

https://github.com/barchart/barchart-ondemand-client-js/blob/master/src/ondemand-client.js#L255

**Comment by Milounas** [comment]
@mvberg Ok thanks
