### ISSUE TITLE
If there is no data available in a request, the server returns a null filled quote in the results.

### ISSUE THREAD

**Issue by AndoniMartin** [barchart/barchart-ondemand-client-js#5]
When requesting a history for a concrete symbol:

`https://ondemand.websol.barchart.com/getHistory.jsonp?symbol=%5EEURUSD&startDate=201706050553&endDate=201706050653&type=minutes&interval=1&apikey=<secret>&callback=jsonpODJSClient_ugfn2gl8mqmvib8
`

if there is no data available, the request returns the follwing JSON instead of a HTTP code 204 or any other indicative for "there is no data":

`jsonpODJSClient_ugfn2gl8mqmvib8({"status":{"code":200,"message":"Success."},"results":[{"symbol":"^EURUSD","timestamp":"1969-12-31T18:00:00-06:00","tradingDay":"1970-01-01","open":null,"high":null,"low":null,"close":null,"volume":null}]});`

Also, notice that the first request is valid so data must be returned or else return an error if there is any problem server-side.

**Comment by mvberg** [comment]
We will take a look internally, and:

1) at least return an empty array when they query results are truly empty
2) hope to change the response code to 204 - assuming it will not break others

For reference, the single "null bar" can be reproduced with a date in the future:

```
https://ondemand.websol.barchart.com/getHistory.jsonp?symbol=AAPL&startDate=201900000000&endDate=201900000000&type=minutes&interval=1
```

**Comment by AndoniMartin** [comment]
Thank you very much, I'll stay tuned waiting for an update. ;)

**Comment by mvberg** [comment]
@AndoniMartin this has been fixed.
